/**
 * Theme -> CSS.
 *
 * This is the one function that turns a theme into a stylesheet, and it is used by BOTH
 * the live preview and the exporter. That is deliberate: it guarantees the preview is
 * byte-for-byte what ships, so there is no class of "looked right in the tool" bug.
 */

import type { ComponentDef, Decls, Theme } from './types.js';
import {
  COLOR_CONTROL_IDS,
  DARK_SCHEME_L,
  GLOBAL_GROUPS,
  emitColor,
} from './tokens/globals.js';
import { globalValue } from './theme.js';

export interface BuildOptions {
  /** Emit the [data-theme=dark] block. */
  dark?: boolean;
  /** Prepend a provenance banner. */
  banner?: boolean;
  themeName?: string;
}

/** All global declarations for the light scheme. */
export function lightDecls(theme: Theme): Decls {
  const out: Decls = {};
  for (const group of GLOBAL_GROUPS) {
    for (const control of group.controls) {
      Object.assign(out, control.emit(globalValue(theme, control.id)));
    }
  }
  return out;
}

/**
 * Dark-scheme declarations.
 *
 * Only the contrast-dependent parts differ: a colour's hue and saturation are the same in
 * both schemes, but "this colour used as text" must be re-derived against a 9%-lightness
 * background or links go unreadable in dark mode. Bulma hardcodes these per scheme; we
 * compute them, so they stay correct for any brand colour.
 */
export function darkDecls(theme: Theme): Decls {
  const out: Decls = {};
  for (const id of COLOR_CONTROL_IDS) {
    const hex = globalValue(theme, id);
    const full = emitColor(id, hex, DARK_SCHEME_L);
    const key = `--bulma-${id}-on-scheme-l`;
    if (full[key]) out[key] = full[key];
  }
  // Any explicit dark-only overrides the user set win over the derived values.
  for (const [controlId, value] of Object.entries(theme.darkGlobals)) {
    const control = GLOBAL_GROUPS.flatMap((g) => g.controls).find((c) => c.id === controlId);
    if (control) Object.assign(out, control.emit(value));
  }
  return out;
}

/**
 * Declarations a global control needs to place on a component selector rather than
 * `:root`, merged across all controls. See ControlDef.emitScoped for why this exists.
 */
export function globalScopedDecls(theme: Theme): Record<string, Decls> {
  const out: Record<string, Decls> = {};
  for (const group of GLOBAL_GROUPS) {
    for (const control of group.controls) {
      if (!control.emitScoped) continue;
      const scoped = control.emitScoped(globalValue(theme, control.id));
      for (const [selector, decls] of Object.entries(scoped)) {
        out[selector] = { ...out[selector], ...decls };
      }
    }
  }
  return out;
}

/** Scoped declarations for one component's overrides, or null if it has none. */
export function componentDecls(theme: Theme, component: ComponentDef): Decls | null {
  const overrides = theme.components[component.id];
  if (!overrides) return null;
  const out: Decls = {};
  for (const control of component.controls) {
    const value = overrides[control.id];
    if (value === undefined) continue;
    Object.assign(out, control.emit(value));
  }
  return Object.keys(out).length ? out : null;
}

function block(selector: string, decls: Decls, indent = '  '): string {
  const body = Object.entries(decls)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join('\n');
  return `${selector} {\n${body}\n}`;
}

export function buildCss(
  theme: Theme,
  components: ComponentDef[],
  opts: BuildOptions = {},
): string {
  const { dark = true, banner = false } = opts;
  const parts: string[] = [];

  if (banner) {
    parts.push(
      [
        '/*',
        ` * ${theme.name}`,
        ' * Generated by Design Forge. Load AFTER bulma.css and extensions.css.',
        ' * Edit the theme in the studio and re-export rather than editing this file.',
        ' */',
      ].join('\n'),
    );
  }

  parts.push('/* Global tokens */');
  parts.push(block(':root', lightDecls(theme)));

  if (dark) {
    const d = darkDecls(theme);
    if (Object.keys(d).length) {
      parts.push('/* Dark scheme: contrast-dependent values re-derived for a dark background */');
      parts.push(block('[data-theme="dark"],\n.theme-dark', d));
    }
  }

  // Global tokens that must reach a component selector. Emitted before the per-component
  // overrides so that an explicit override always wins on source order.
  const globalScoped = globalScopedDecls(theme);
  if (Object.keys(globalScoped).length) {
    parts.push('/* Global tokens that Bulma re-declares on the component itself */');
    for (const [selector, decls] of Object.entries(globalScoped)) {
      parts.push(block(selector, decls));
    }
  }

  const scoped = components
    .map((c) => ({ c, decls: componentDecls(theme, c) }))
    .filter((x): x is { c: ComponentDef; decls: Decls } => x.decls !== null);

  if (scoped.length) {
    parts.push('/* Component overrides */');
    for (const { c, decls } of scoped) {
      parts.push(`/* ${c.name} */\n${block(c.selector, decls)}`);
    }
  }

  return `${parts.join('\n\n')}\n`;
}

/** Compact form used to hot-swap the preview iframe's style tag. */
export function buildPreviewCss(theme: Theme, components: ComponentDef[]): string {
  return buildCss(theme, components, { dark: true, banner: false });
}
